### ISSUE TITLE
[feat] Dockerize the project please

### ISSUE THREAD

**Issue by accforgithubtest** [mcanyucel/compose-version-check#1]
Absolutely brilliant idea ! I have been looking for something like this for a while and all other options only alert you for the updates available foe the same version or latest tags.

I typically pin the version numbers to avoid software breaking down, however I would sit and upgrade the versions to latest when I can find a few hours of quite time, so I can deal with any issues from upgrades, and there were no software to alert me when there is a version upgrade available.

I would request you consider dockerizing this project so running this in a self hosted setup will be easy.

Ideally, we would be mounting the parent folder under which all the docker compose files are as read-only volume, and this software does what it does.

Thanks again for creating this !

**Comment by mcanyucel** [comment]
Thanks!

Added docker and compose support. The docker image can handle scheduled controls. See readme and 70f90d8 for details.
